name: Enforce valid gitsign signatures

on:
  pull_request:
    # types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - run: go install github.com/sigstore/gitsign@latest
      - run: gitsign version
      - run: gitsign verify --certificate-identity-regexp="^.*@oplabs.co$" --certificate-oidc-issuer="https://accounts.google.com" HEAD