name: Enforce valid gitsign signatures

on:
  pull_request:
    # types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - run: apk add gitsign
      - run: gitsign version
      - run: gitsign verify --certificate-identity-regexp="^.*@oplabs.co$" --certificate-oidc-issuer="https://accounts.google.com" HEAD